apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-httpbin

resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/ingress.yaml
  - ../../base/configmap.yaml

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - path: patches.yaml
    target:
      kind: Deployment
      name: go-httpbin
